apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
  MYSQL_USER: cm9vdA==              # base64 encoded "root"
  MYSQL_PASSWORD: cGFzc3dvcmQ=       # base64 encoded "password"